/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author Lenovo
 */
import entity.Movie;
import entity.Showtime;
import DAO.MovieDAO;
import DAO.ShowtimeDAO;
import DAO.RoomDAO;
import cinema.Database;
import entity.Room;
import java.awt.Color;
import java.awt.Component;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.*;
public class TicketSale extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TicketSale.class.getName());
    private final ShowtimeDAO showtimeDAO;
    private final MovieDAO movieDAO;
    private final RoomDAO roomDAO;
    private Color defaultcolor;
    private Double ticketPrice=0.;
    private Double servicePrice=0.;
    private Double totalPrice=0.;
    /**
     * Creates new form TicketSale
     */
    public TicketSale() {
        movieDAO=new MovieDAO();
        showtimeDAO=new ShowtimeDAO();
        roomDAO=new RoomDAO();
        initComponents();
        loadMovie();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SalePane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MovieComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        ShowtimeComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        roomLabel = new javax.swing.JLabel();
        seatPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ticketLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        serviceLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        serviceBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Tên phim");

        MovieComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovieComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Suất chiếu");

        ShowtimeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowtimeComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("Phòng chiếu:");

        javax.swing.GroupLayout seatPanelLayout = new javax.swing.GroupLayout(seatPanel);
        seatPanel.setLayout(seatPanelLayout);
        seatPanelLayout.setHorizontalGroup(
            seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );
        seatPanelLayout.setVerticalGroup(
            seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 231, Short.MAX_VALUE)
        );

        jLabel4.setText("Giá vé:");

        jLabel6.setText("Dịch vụ:");

        jLabel8.setText("Tổng tiền:");

        serviceBtn.setText("Tiếp");
        serviceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Hủy");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(roomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(MovieComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ShowtimeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))))
                        .addContainerGap(497, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(seatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cancelBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(serviceBtn)
                                .addGap(31, 31, 31))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(serviceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                    .addComponent(ticketLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MovieComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowtimeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(roomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(seatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(ticketLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(serviceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(serviceBtn)
                            .addComponent(cancelBtn))
                        .addGap(56, 56, 56))))
        );

        SalePane.addTab("tab1", jPanel1);

        jLabel5.setText("Service");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(441, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel5)
                .addContainerGap(268, Short.MAX_VALUE))
        );

        SalePane.addTab("tab2", jPanel2);

        jLabel7.setText("Invoice");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(441, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel7)
                .addContainerGap(273, Short.MAX_VALUE))
        );

        SalePane.addTab("tab3", jPanel3);

        getContentPane().add(SalePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -40, 750, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void MovieComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovieComboBoxActionPerformed
        try {
            String movieId = ((String) MovieComboBox.getSelectedItem()).split(" - ")[0];
            ShowtimeComboBox.removeAllItems();
            List<Showtime> showtimes = showtimeDAO.getShowtimesByMovieId(movieId);
            for (Showtime showtime : showtimes) {
                ShowtimeComboBox.addItem(showtime.getStart_time() + " - " + showtime.getEnd_time());
            }
            reset();
        } catch(SQLException | ClassNotFoundException ex){
            JOptionPane.showMessageDialog(this,"Lỗi"+ex.getMessage());
        }        
    }//GEN-LAST:event_MovieComboBoxActionPerformed

    private void ShowtimeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowtimeComboBoxActionPerformed
        try {
            Object selected=ShowtimeComboBox.getSelectedItem();
            if(selected==null){
               return;
            }
            String showDate = ((String) selected).split(" - ")[0];   
            String sql = "select * from showtime s join theater t on s.Theater_ID=t.Theater_ID where start_time=?";
            PreparedStatement pst = Database.getDB().connect().prepareStatement(sql);
            pst.setString(1, showDate);
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                 roomLabel.setText(rs.getString("theater_id") + " - " + rs.getString("theater_name"));
            }
            getSeatTable();
            reset();
        } catch(SQLException | ClassNotFoundException ex){
            JOptionPane.showMessageDialog(this,"Lỗi"+ex.getMessage());
        }          
    }//GEN-LAST:event_ShowtimeComboBoxActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
      for (Component comp : seatPanel.getComponents()) {
         if (comp instanceof JButton btnGhe) {
            if (btnGhe.isEnabled()) {    
                btnGhe.setBackground(defaultcolor);
            }
         }
      }
        MovieComboBox.setSelectedIndex(0);
        ShowtimeComboBox.setSelectedIndex(0);      
        reset();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void serviceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceBtnActionPerformed
        if(totalPrice==0.){
            JOptionPane.showMessageDialog(this,"Hãy chọn ghế");
            return;
        }
        SalePane.setSelectedIndex(1);
    }//GEN-LAST:event_serviceBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    private void getSeatTable(){
        String roomId=((String) roomLabel.getText()).split(" - ")[0];
        String showDate = ((String) ShowtimeComboBox.getSelectedItem()).split(" - ")[0];
        try {
            Room room=roomDAO.findById(roomId).orElse(null);
            Showtime show=showtimeDAO.getShowtimeByDate(showDate).orElse(null);
            seatPanel.removeAll();
            seatPanel.setLayout(new java.awt.GridLayout(room.getRowNum(),room.getSeatPerRow(),5,5));
            for (int i = 0; i < room.getRowNum(); i++) {
                char hang = (char) ('A' + i);
                for (int j = 1; j <= room.getSeatPerRow(); j++) {
                    String seatNum= "" + hang + j;
                    JButton btnSeat = new JButton(seatNum);

            if (!show.seatAvailable(seatNum)) {
                btnSeat.setBackground(Color.LIGHT_GRAY);
                btnSeat.setEnabled(false);
                btnSeat.setToolTipText("Ghế đã được đặt");
            } else {
                defaultcolor=btnSeat.getBackground();
                btnSeat.addActionListener((java.awt.event.ActionEvent e) -> {
                      pickSeat(btnSeat);
                });
            }
                seatPanel.add(btnSeat);
                }              
            }
            seatPanel.revalidate();
            seatPanel.repaint();
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this,"Lỗi"+ex.getMessage());
        }
    }
    private void pickSeat(javax.swing.JButton btn){
     try{   
      String showDate = ((String) ShowtimeComboBox.getSelectedItem()).split(" - ")[0];
      Showtime show=showtimeDAO.getShowtimeByDate(showDate).orElse(null);
      if (btn.getBackground().equals(defaultcolor)) {
        btn.setBackground(Color.GREEN);
        ticketPrice+=show.getShow_price();
        totalPrice+=show.getShow_price();
        ticketLabel.setText(String.valueOf(ticketPrice));
        totalLabel.setText(String.valueOf(totalPrice));
        //txtSelectedSeats.append(btn.getText() + " ");
      }
      else if (btn.getBackground().equals(Color.GREEN)) {
        btn.setBackground(defaultcolor);
        ticketPrice-=show.getShow_price();
        totalPrice-=show.getShow_price();
        ticketLabel.setText(String.valueOf(ticketPrice));     
        totalLabel.setText(String.valueOf(totalPrice));        
        //String ghe = btn.getText() + " ";
        //txtSelectedSeats.setText(
         //   txtSelectedSeats.getText().replace(ghe, "")
        //);
      }}catch(SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this,"Lỗi"+ex.getMessage());
        }
    }
    private void reset(){
        ticketPrice=0.;
        totalPrice=0.;
        ticketLabel.setText(String.valueOf(ticketPrice));
        totalLabel.setText(String.valueOf(totalPrice));     
    }    
    private void loadMovie(){
        try {
            MovieComboBox.removeAllItems();
            List<Movie> movies = movieDAO.findAll();
            for (Movie movie : movies) {
                MovieComboBox.addItem(movie.getId() + " - " + movie.getTitle());
            }
        } catch(SQLException | ClassNotFoundException ex){
            JOptionPane.showMessageDialog(this,"Lỗi"+ex.getMessage());
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TicketSale().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> MovieComboBox;
    private javax.swing.JTabbedPane SalePane;
    private javax.swing.JComboBox<String> ShowtimeComboBox;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel roomLabel;
    private javax.swing.JPanel seatPanel;
    private javax.swing.JButton serviceBtn;
    private javax.swing.JLabel serviceLabel;
    private javax.swing.JLabel ticketLabel;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
